lab:
  hosts:
    lab-1:
      ansible_host: 10.77.1.31
    lab-2:
      ansible_host: 10.77.1.32
    lab-3:
      ansible_host: 10.77.1.38
    lab-4:
      ansible_host: 10.77.1.39


rhel:
  hosts:
    lab-1:
    lab-2:

debian:
  hosts:
    lab-3:
    lab-4:

linux:
  children:
    rhel:
    debian:
