- name: Protect against CVE-2016-5696
  hosts: "{{ target_hosts | default('linux') }}"
  become: yes

  tasks:
    - name: CVE-2016-5696 | Limit TCP challenge ACK limit
      sysctl:
        name: net.ipv4.tcp_challenge_ack_limit
        value: 999999999
        sysctl_set: yes
